#!/bin/bash
#This script is executed every time your instance is spawned.

mkdir ~/boxes
mkdir ~/repos

git clone https://github.com/emancipat3r/OSCP.git ~/repos/OSCP/

sudo apt-get install tmux -y

export PASS=$(cat ~/Desktop/my_credentials.txt | grep -i password | awk -F " " '{ print $2 }')

echo $PASS | chsh -s $(which zsh)

echo "Y" | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo "104" | bash -c "$(wget -qO- https://git.io/vQgMr)"
